### ISSUE TITLE
Extension curlybracket.vlocode has provided an invalid tree item

### ISSUE THREAD

**Issue by egblotta** [Codeneos/vlocode#388]
Type: <b>Bug</b>

Extension curlybracket.vlocode has provided an invalid tree item.

Extension version: 0.16.22
VS Code version: Code 1.72.1 (129500ee4c8ab7263461ffe327268ba56b9f210d, 2022-10-10T17:22:48.346Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 3 3200G with Radeon Vega Graphics     (4 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.69GB free)|
|Process Argv|--crash-reporter-id 9bd5f639-05fa-46fe-89b9-f486a0667c6e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256859
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904
pyindex848cf:30577861
fc301958:30573243

```

</details>

**Comment by Codeneos** [comment]
I checked this error, it is related to a regression bug in Vscode and if it doesn't cause any errors you can ignore it.

It happens in version 1.70.0 of vscode and is resolved in  the august patch. 

Check if you are running the latest version of vscode, 1.71 as of the time of writing.

**Comment by egblotta** [comment]
Hi @Codeneos, thank you for your answer. I already solve it by installing an old version of Vscode (1.71.2) and the last version of Vlocode.

**Comment by irfanlai** [comment]
My VS code is updated with ver 1.18.2
Vlocity is v0.17.11

I am still facing the same issue.

**Comment by Codeneos** [comment]
@irfanlai - could you open a new issue for this and share the log and steps to reproduce? I'll have a look at it later and see if I can reproduce it locally.
